In [2]:
pi = 3.1416

In [4]:
eval("pi")

3.1416

In [8]:
eval("pi + 1")

4.1416

In [2]:
import torch
import torch.nn as nn

# Size: [batch_size, seq_len, input_size]
input = torch.randn(12, 384, 768)

lstm = nn.LSTM(input_size=768, hidden_size=512, batch_first=True)

output, _ = lstm(input)
output.size()  # => torch.Size([12, 384, 512])

torch.Size([12, 384, 512])

In [10]:
_

(tensor([[[-0.3133, -0.0560, -0.0300,  ..., -0.1177,  0.0696, -0.0292],
          [-0.0567,  0.0413,  0.0857,  ..., -0.3615,  0.0202, -0.0169],
          [ 0.1724, -0.0754,  0.2294,  ..., -0.0077, -0.1161, -0.1695],
          ...,
          [ 0.2040,  0.0081, -0.1954,  ...,  0.0066, -0.0281, -0.0578],
          [-0.1028, -0.0622,  0.1658,  ..., -0.1051, -0.0898, -0.0103],
          [ 0.2462, -0.2415,  0.0713,  ...,  0.0795,  0.1604,  0.0737]]],
        grad_fn=<StackBackward0>),
 tensor([[[-0.4943, -0.1270, -0.0800,  ..., -0.2138,  0.1948, -0.0354],
          [-0.1946,  0.0653,  0.1514,  ..., -0.8019,  0.0326, -0.0212],
          [ 0.3044, -0.1881,  0.7797,  ..., -0.0118, -0.2313, -0.4993],
          ...,
          [ 0.2973,  0.0111, -0.4495,  ...,  0.0225, -0.0443, -0.1122],
          [-0.4313, -0.0902,  0.4414,  ..., -0.2260, -0.2237, -0.0234],
          [ 0.3705, -0.5724,  0.1008,  ...,  0.1565,  0.3874,  0.1062]]],
        grad_fn=<StackBackward0>))

In [19]:
# With square kernels and equal stride
# m = nn.Conv2d(16, 33, 3, stride=2)

m = nn.Conv2d(in_channels=16, out_channels=33, kernel_size=3)

# # non-square kernels and unequal stride and with padding
# m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
# # non-square kernels and unequal stride and with padding and dilation
# m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))
input = torch.randn(20, 16, 50, 100)
output = m(input)

In [20]:
output.size()

torch.Size([20, 33, 48, 98])

In [21]:
m = nn.Conv2d(16, 33, 3, stride=2)
input = torch.randn(20, 16, 50, 100)
output = m(input)
output.size()

torch.Size([20, 33, 24, 49])

In [23]:
 m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))

# # non-square kernels and unequal stride and with padding
# m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
# # non-square kernels and unequal stride and with padding and dilation
# m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))
input = torch.randn(20, 16, 50, 100)
output = m(input)
output.size()

torch.Size([20, 33, 28, 100])

In [26]:
# small NN model
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


In [27]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [28]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [29]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([7], device='cuda:0')


In [31]:
X.size()

torch.Size([1, 28, 28])

In [32]:
logits.size()

torch.Size([1, 10])

In [33]:
logits

tensor([[-0.0190, -0.0795, -0.0254, -0.0495, -0.0407,  0.0087,  0.0285,  0.0338,
         -0.0805, -0.0702]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
x_data.unsqueeze(1)

tensor([[[1, 2]],

        [[3, 4]]])

In [6]:
x = torch.tensor([1, 2, 3, 4])

In [7]:
x.unsqueeze(1)

tensor([[1],
        [2],
        [3],
        [4]])

In [8]:
x.size()

torch.Size([4])

In [9]:
x.unsqueeze(1).size()

torch.Size([4, 1])

In [10]:
X = torch.rand(5,1,120)

In [12]:
X.unsqueeze(1).size()

torch.Size([5, 1, 1, 120])