In [6]:
pi = 3.1416

In [7]:
eval("pi")

3.1416

In [8]:
eval("pi + 1")

4.1416

In [2]:
import torch
import torch.nn as nn

# Size: [batch_size, seq_len, input_size]
input = torch.randn(12, 384, 768)

lstm = nn.LSTM(input_size=768, hidden_size=512, batch_first=True)

output, _ = lstm(input)
output.size()  # => torch.Size([12, 384, 512])

torch.Size([12, 384, 512])

In [10]:
_

(tensor([[[ 0.0660,  0.1668,  0.1254,  ..., -0.2001,  0.0347,  0.2424],
          [-0.0994, -0.0378,  0.0519,  ...,  0.2637, -0.0680, -0.1766],
          [-0.0943, -0.2104,  0.1308,  ...,  0.1129,  0.0485, -0.2648],
          ...,
          [ 0.2546,  0.2193,  0.0599,  ...,  0.0559, -0.0607, -0.1723],
          [-0.2660,  0.1328,  0.0079,  ..., -0.1087, -0.2487,  0.0459],
          [-0.1117, -0.0449,  0.4685,  ..., -0.0911,  0.1251, -0.0602]]],
        grad_fn=<StackBackward0>),
 tensor([[[ 0.1407,  0.2978,  0.5048,  ..., -0.4086,  0.0849,  0.5962],
          [-0.1802, -0.1695,  0.0793,  ...,  0.4429, -0.2510, -0.3452],
          [-0.1369, -0.4153,  0.1792,  ...,  0.3951,  0.1991, -0.5190],
          ...,
          [ 0.4967,  0.3190,  0.1362,  ...,  0.1281, -0.0828, -0.4109],
          [-0.4541,  0.1759,  0.0147,  ..., -0.1813, -0.7096,  0.1472],
          [-0.2492, -0.2303,  0.7177,  ..., -0.1600,  0.5464, -0.1239]]],
        grad_fn=<StackBackward0>))

In [11]:
# With square kernels and equal stride
# m = nn.Conv2d(16, 33, 3, stride=2)

m = nn.Conv2d(in_channels=16, out_channels=33, kernel_size=3)

# # non-square kernels and unequal stride and with padding
# m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
# # non-square kernels and unequal stride and with padding and dilation
# m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))
input = torch.randn(20, 16, 50, 100)
output = m(input)

In [12]:
output.size()

torch.Size([20, 33, 48, 98])

In [13]:
m = nn.Conv2d(16, 33, 3, stride=2)
input = torch.randn(20, 16, 50, 100)
output = m(input)
output.size()

torch.Size([20, 33, 24, 49])

In [14]:
 m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))

# # non-square kernels and unequal stride and with padding
# m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
# # non-square kernels and unequal stride and with padding and dilation
# m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))
input = torch.randn(20, 16, 50, 100)
output = m(input)
output.size()

torch.Size([20, 33, 28, 100])

In [15]:
# small NN model
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


In [16]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [17]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [18]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([5], device='cuda:0')


In [19]:
X.size()

torch.Size([1, 28, 28])

In [20]:
logits.size()

torch.Size([1, 10])

In [21]:
logits

tensor([[-0.1119, -0.0031,  0.0117,  0.0120,  0.0352,  0.1063, -0.1120,  0.0162,
          0.0227,  0.0593]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [22]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [23]:
x_data

tensor([[1, 2],
        [3, 4]])

In [24]:
x_data.unsqueeze(1)

tensor([[[1, 2]],

        [[3, 4]]])

In [25]:
x = torch.tensor([1, 2, 3, 4])

In [26]:
x.unsqueeze(1)

tensor([[1],
        [2],
        [3],
        [4]])

In [27]:
x.size()

torch.Size([4])

In [28]:
x.unsqueeze(1).size()

torch.Size([4, 1])

In [29]:
X = torch.rand(5,1,120)

In [30]:
X.unsqueeze(1).size()

torch.Size([5, 1, 1, 120])

In [31]:
# With square kernels and equal stride
m = nn.Conv2d(1, 400, (3,3))
# non-square kernels and unequal stride and with padding
# m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
# # non-square kernels and unequal stride and with padding and dilation
# m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))
# input = torch.randn(20, 16, 50, 100)
# output = m(input)

In [32]:
m

Conv2d(1, 400, kernel_size=(3, 3), stride=(1, 1))

In [33]:
# input = torch.randn(20, 16, 50, 100)
input = torch.randn(22, 1, 3, 125)

In [34]:
output = m(input)

In [35]:
output.size()

torch.Size([22, 400, 1, 123])

In [36]:
## word cnn
word_cnn3 = nn.Conv2d(in_channels=1, out_channels=400, kernel_size=(3, 100), padding=(1,0))

In [37]:
word_cnn3

Conv2d(1, 400, kernel_size=(3, 100), stride=(1, 1), padding=(1, 0))

In [38]:
word_embeds = torch.randn(11,100)

In [39]:
word_embeds = word_embeds.unsqueeze(1)

In [40]:
word_embeds = word_embeds.unsqueeze(1)

In [41]:
word_embeds.size()

torch.Size([11, 1, 1, 100])

In [42]:
output = word_cnn3(word_embeds)

In [43]:
output.size()

torch.Size([11, 400, 1, 1])

In [44]:
output.squeeze().size()

torch.Size([11, 400])

In [45]:
word_cnn_out3 = torch.randn(37, 400, 3, 76)

In [46]:
mp = nn.functional.max_pool2d(output,
                            kernel_size=(word_cnn_out3.size(2), 76)).view(word_cnn_out3.size(0), 400)

RuntimeError: Given input size: (400x1x1). Calculated output size: (400x0x0). Output size is too small

In [ ]:
mp.size()

In [47]:
b = torch.randn(11,400,1,1)

In [48]:
b.size()

torch.Size([11, 400, 1, 1])

In [49]:
c = b.squeeze(2)

In [50]:
c.squeeze(1).size()

torch.Size([11, 400, 1])

In [51]:
b.squeeze(2).size()

torch.Size([11, 400, 1])

In [ ]:
b

In [58]:
import time
atime = time.time()

In [59]:
import time
btime =time.time()

In [60]:
btime - atime

0.6775588989257812

In [61]:
13//4

3

In [4]:
word_cnn_out3 = torch.randn(26, 400, 1, 21)

In [12]:
word_cnn_out3 = word_cnn_out3.squeeze(2)

In [14]:
word_cnn_out3.size()

torch.Size([26, 400, 21])

In [15]:
word_cnn_out3 = word_cnn_out3.unsqueeze(3)

In [19]:
word_embeds = nn.functional.max_pool2d(word_cnn_out3,
                             kernel_size=(word_cnn_out3.size(2), 1)).view(word_cnn_out3.size(0), 400)

In [20]:
word_embeds.size()

torch.Size([26, 400])